# Generated by Django 4.1.4 on 2022-12-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0003_imam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('narrator', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('book_vol_no', models.IntegerField()),
                ('book_page_no', models.IntegerField()),
                ('book_narration_no', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ahadis.book')),
                ('imam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ahadis.imam')),
            ],
            options={
                'db_table': 'Narration',
            },
        ),
    ]
