# Generated by Django 4.1.4 on 2023-01-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0007_contentsummarytree_alphabet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentsummarytree',
            old_name='subject_5',
            new_name='expression',
        ),
    ]
