# Generated by Django 4.1.4 on 2023-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0008_rename_subject_5_contentsummarytree_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='includes_verse',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
