# Generated by Django 4.1.4 on 2023-01-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0009_narration_includes_verse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narration',
            name='includes_verse',
        ),
    ]
