# Generated by Django 4.1.4 on 2023-02-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0010_remove_narration_includes_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source_type',
            field=models.CharField(default='cd', max_length=20),
            preserve_default=False,
        ),
    ]
