# Generated by Django 4.1.4 on 2023-02-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0011_book_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsummarytree',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.narration'),
        ),
        migrations.AlterField(
            model_name='narration',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.book'),
        ),
        migrations.AlterField(
            model_name='narration',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.imam'),
        ),
        migrations.AlterField(
            model_name='narrationfootnote',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.narration'),
        ),
        migrations.AlterField(
            model_name='narrationsubject',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.narration'),
        ),
        migrations.AlterField(
            model_name='narrationverse',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.narration'),
        ),
        migrations.AlterField(
            model_name='narrationverse',
            name='quran_verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.quranverse'),
        ),
    ]
