# Generated by Django 4.1.4 on 2023-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0014_alter_narrationverse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narration',
            name='narrator',
            field=models.TextField(),
        ),
    ]
