# Generated by Django 4.1.4 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0014_alter_narrationverse_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Book1',
            },
        ),
        migrations.CreateModel(
            name='ContentSummaryTree1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ContentSummaryTree1',
            },
        ),
        migrations.CreateModel(
            name='Imam1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Imam1',
            },
        ),
        migrations.CreateModel(
            name='Narration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Narration1',
            },
        ),
        migrations.CreateModel(
            name='NarrationFootnote1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField()),
            ],
            options={
                'db_table': 'NarrationFootnote1',
            },
        ),
        migrations.CreateModel(
            name='NarrationSubject1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'NarrationSubject1',
            },
        ),
        migrations.CreateModel(
            name='QuranVerse1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_content', models.TextField()),
            ],
            options={
                'db_table': 'QuranVerse1',
            },
        ),
        migrations.AlterField(
            model_name='contentsummarytree',
            name='alphabet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='narration',
            name='narrator',
            field=models.TextField(),
        ),
    ]
