# Generated by Django 4.1.4 on 2023-04-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0015_alter_narration_narrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsummarytree',
            name='alphabet',
            field=models.CharField(max_length=200),
        ),
    ]
