# Generated by Django 4.1.4 on 2023-05-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0016_narration1_book_narration1_imam'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrationsubject1',
            name='narration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ahadis.narration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='narration1',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration', to='ahadis.imam1'),
        ),
    ]
