# Generated by Django 4.1.4 on 2023-05-27 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0017_narrationsubject1_narration_alter_narration1_imam'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsummarytree1',
            name='expression',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentsummarytree1',
            name='subject_1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentsummarytree1',
            name='subject_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentsummarytree1',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='narrationsubject1',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='ahadis.narration1'),
        ),
    ]
