# Generated by Django 4.1.4 on 2023-05-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0018_contentsummarytree1_expression_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentsummarytree1',
            old_name='subject_2',
            new_name='sub_subject',
        ),
        migrations.RenameField(
            model_name='contentsummarytree1',
            old_name='subject_1',
            new_name='subject',
        ),
    ]
