# Generated by Django 4.1.4 on 2023-05-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0016_alter_contentsummarytree_alphabet'),
        ('ahadis', '0019_rename_subject_2_contentsummarytree1_sub_subject_and_more'),
    ]

    operations = [
    ]
