# Generated by Django 4.2.3 on 2023-07-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0020_merge_20230527_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentSummaryTree1',
        ),
        migrations.RemoveField(
            model_name='narration1',
            name='book',
        ),
        migrations.RemoveField(
            model_name='narration1',
            name='imam',
        ),
        migrations.DeleteModel(
            name='NarrationFootnote1',
        ),
        migrations.RemoveField(
            model_name='narrationsubject1',
            name='narration',
        ),
        migrations.DeleteModel(
            name='QuranVerse1',
        ),
        migrations.AlterField(
            model_name='contentsummarytree',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_summary_tree', to='ahadis.narration'),
        ),
        migrations.AlterField(
            model_name='narrationfootnote',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnote', to='ahadis.narration'),
        ),
        migrations.DeleteModel(
            name='Book1',
        ),
        migrations.DeleteModel(
            name='Imam1',
        ),
        migrations.DeleteModel(
            name='Narration1',
        ),
        migrations.DeleteModel(
            name='NarrationSubject1',
        ),
    ]
