# Generated by Django 4.2.3 on 2024-02-11 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahadis', '0022_alter_narrationfootnote_narration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsummarytree',
            name='expression',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contentsummarytree',
            name='subject_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contentsummarytree',
            name='subject_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contentsummarytree',
            name='subject_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contentsummarytree',
            name='subject_4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contentsummarytree',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='narrationfootnote',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='narrationfootnote',
            name='expression',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('narration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.narration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookmark',
                'unique_together': {('narration', 'user')},
            },
        ),
    ]
