# Generated by Django 4.2.3 on 2024-03-17 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahadis', '0023_alter_contentsummarytree_expression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNarration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('narration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_narrations', to='ahadis.narration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserNarration',
                'unique_together': {('narration', 'user')},
            },
        ),
    ]
