# Generated by Django 4.2.3 on 2024-07-13 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahadis', '0024_narration_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='ahadis.narration'),
        ),
        migrations.CreateModel(
            name='SharedNarrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('narration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahadis.narration')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SharedNarrations',
                'unique_together': {('narration', 'sender')},
            },
        ),
    ]
