# Generated by Django 4.2.3 on 2024-07-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0025_alter_bookmark_narration_sharednarrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsummarytree',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='narrationfootnote',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='narrationsubject',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='narrationverse',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='narrationverse',
            name='narration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration_verses', to='ahadis.narration'),
        ),
    ]
