# Generated by Django 4.2.3 on 2024-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0026_alter_contentsummarytree_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
