# Generated by Django 4.2.3 on 2024-08-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0027_narration_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednarrations',
            name='receiver_narration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_narrations', to='ahadis.narration'),
        ),
    ]
