# Generated by Django 4.2.3 on 2024-09-03 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahadis', '0029_alter_sharednarrations_narration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednarrations',
            name='receiver_narration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_narration', to='ahadis.narration'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Not Registered'), (2, 'Registered'), (4, 'Super Admin'), (8, 'Tagger'), (16, 'Admin'), (32, 'Checker Admin')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
