# Generated by Django 4.2.3 on 2024-09-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahadis', '0030_alter_sharednarrations_receiver_narration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
